#!/usr/bin/env node
/**
 * Single generator: reads src/data/catalog.json (the source of truth) and emits every
 * derived artifact so they can never drift:
 *
 *   1. .claude-plugin/marketplace.json   — repo-root manifest, relative plugin sources
 *                                          (works via `/plugin marketplace add probablybadmove/agora`)
 *   2. public/marketplace.json           — hosted manifest, absolute git-subdir sources
 *                                          (works via `/plugin marketplace add https://gagansingh.tech/marketplace.json`)
 *   3. supabase/seed.sql                 — categories + plugins INSERTs for the database
 *
 * Run:  npm run build:catalog   (or: node scripts/build-catalog.mjs)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const catalog = JSON.parse(readFileSync(resolve(root, 'src/data/catalog.json'), 'utf8'));
const { marketplace, categories, plugins } = catalog;
const categoryName = Object.fromEntries(categories.map((c) => [c.slug, c.name]));

/* 1 + 2 — marketplace manifests --------------------------------------------------- */

function pluginEntry(p) {
  return {
    name: p.name,
    source: p.source,
    description: p.description,
    category: categoryName[p.category] ?? p.category,
    keywords: p.keywords.slice(0, 6),
    author: { name: p.author.name },
  };
}

const base = {
  $schema: 'https://json.schemastore.org/claude-code-marketplace-manifest.json',
  name: marketplace.name,
  owner: marketplace.owner,
  description: marketplace.description,
  version: marketplace.version,
  metadata: {
    description: marketplace.description,
    version: marketplace.version,
  },
};

// Repo-root manifest: relative sources.
const repoManifest = { ...base, plugins: plugins.map(pluginEntry) };
mkdirSync(resolve(root, '.claude-plugin'), { recursive: true });
writeFileSync(
  resolve(root, '.claude-plugin/marketplace.json'),
  JSON.stringify(repoManifest, null, 2) + '\n'
);

// Hosted manifest: rewrite relative sources into absolute git-subdir sources.
const hostedManifest = {
  ...base,
  plugins: plugins.map((p) => {
    const entry = pluginEntry(p);
    entry.source = {
      source: 'git-subdir',
      url: marketplace.repoUrl,
      path: p.source.replace(/^\.\//, ''),
    };
    return entry;
  }),
};
mkdirSync(resolve(root, 'public'), { recursive: true });
writeFileSync(
  resolve(root, 'public/marketplace.json'),
  JSON.stringify(hostedManifest, null, 2) + '\n'
);

/* 3 — Supabase seed --------------------------------------------------------------- */

const q = (v) => `'${String(v).replace(/'/g, "''")}'`;
const arr = (xs) => `ARRAY[${xs.map(q).join(', ')}]::text[]`;

const catRows = categories
  .map(
    (c, i) =>
      `  (${q(c.slug)}, ${q(c.name)}, ${q(c.description)}, ${q(c.glyph)}, ${q(c.color)}, ${i})`
  )
  .join(',\n');

const pluginRows = plugins
  .map(
    (p) =>
      `  (${q(p.slug)}, ${q(p.name)}, ${q(p.displayName)}, ${q(p.description)}, ${q(
        p.longDescription
      )}, ${q(p.category)}, ${q(p.kind)}, ${arr(p.keywords)}, ${q(p.invocation)}, ${q(p.color)}, ${q(
        p.glyph
      )}, ${q(p.version)}, ${q(p.license)}, ${q(p.author.name)}, ${q(p.author.url)}, ${q(
        p.source
      )}, ${p.featured ? 'true' : 'false'})`
  )
  .join(',\n');

const seedSql = `-- Generated by scripts/build-catalog.mjs from src/data/catalog.json — do not edit by hand.
-- Idempotent: safe to re-run. Apply after the migration in supabase/migrations/.

insert into public.categories (slug, name, description, glyph, color, sort) values
${catRows}
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  glyph = excluded.glyph,
  color = excluded.color,
  sort = excluded.sort;

insert into public.plugins (
  slug, name, display_name, description, long_description, category, kind, keywords,
  invocation, color, glyph, version, license, author_name, author_url, source, featured
) values
${pluginRows}
on conflict (slug) do update set
  name = excluded.name,
  display_name = excluded.display_name,
  description = excluded.description,
  long_description = excluded.long_description,
  category = excluded.category,
  kind = excluded.kind,
  keywords = excluded.keywords,
  invocation = excluded.invocation,
  color = excluded.color,
  glyph = excluded.glyph,
  version = excluded.version,
  license = excluded.license,
  author_name = excluded.author_name,
  author_url = excluded.author_url,
  source = excluded.source,
  featured = excluded.featured,
  updated_at = now();
`;

mkdirSync(resolve(root, 'supabase'), { recursive: true });
writeFileSync(resolve(root, 'supabase/seed.sql'), seedSql);

console.log(
  `Generated:\n  .claude-plugin/marketplace.json (${plugins.length} plugins, relative sources)\n  public/marketplace.json (${plugins.length} plugins, git-subdir sources)\n  supabase/seed.sql (${categories.length} categories, ${plugins.length} plugins)`
);
