#!/usr/bin/env node
/**
 * Single generator: reads src/data/catalog.json (the source of truth) and emits every
 * derived artifact so they can never drift:
 *
 *   1. .claude-plugin/marketplace.json   — repo-root manifest
 *   2. public/marketplace.json           — hosted manifest (absolute sources)
 *   3. supabase/seed.sql                 — categories + plugins INSERTs for the database
 *
 * Plugin sources:
 *   - first-party plugins (live in /plugins here): relative source in the repo manifest,
 *     git-subdir source in the hosted manifest.
 *   - community plugins (community:true, repo:"owner/repo"): a github source in BOTH manifests,
 *     so the plugin stays in the submitter's own repo.
 *
 * Run:  npm run build:catalog   (or: node scripts/build-catalog.mjs)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const catalog = JSON.parse(readFileSync(resolve(root, 'src/data/catalog.json'), 'utf8'));
const { marketplace, categories, plugins } = catalog;
const categoryName = Object.fromEntries(categories.map((c) => [c.slug, c.name]));

/* 1 + 2 — marketplace manifests --------------------------------------------------- */

const isCommunity = (p) => Boolean(p.community && p.repo);

function githubSource(p) {
  const s = { source: 'github', repo: p.repo };
  if (p.ref) s.ref = p.ref;
  return s;
}

function repoSource(p) {
  return isCommunity(p) ? githubSource(p) : p.source;
}

function hostedSource(p) {
  return isCommunity(p)
    ? githubSource(p)
    : { source: 'git-subdir', url: marketplace.repoUrl, path: p.source.replace(/^\.\//, '') };
}

function entry(p, source) {
  const e = {
    name: p.name,
    source,
    description: p.description,
    category: categoryName[p.category] ?? p.category,
    keywords: p.keywords.slice(0, 6),
    author: { name: p.author.name },
  };
  if (p.homepage) e.homepage = p.homepage;
  if (isCommunity(p)) e.repository = `https://github.com/${p.repo}`;
  return e;
}

const base = {
  $schema: 'https://json.schemastore.org/claude-code-marketplace-manifest.json',
  name: marketplace.name,
  owner: marketplace.owner,
  description: marketplace.description,
  version: marketplace.version,
  metadata: { description: marketplace.description, version: marketplace.version },
};

const repoManifest = { ...base, plugins: plugins.map((p) => entry(p, repoSource(p))) };
const hostedManifest = { ...base, plugins: plugins.map((p) => entry(p, hostedSource(p))) };

mkdirSync(resolve(root, '.claude-plugin'), { recursive: true });
writeFileSync(
  resolve(root, '.claude-plugin/marketplace.json'),
  JSON.stringify(repoManifest, null, 2) + '\n'
);
mkdirSync(resolve(root, 'public'), { recursive: true });
writeFileSync(
  resolve(root, 'public/marketplace.json'),
  JSON.stringify(hostedManifest, null, 2) + '\n'
);

/* 3 — Supabase seed --------------------------------------------------------------- */

const q = (v) => `'${String(v).replace(/'/g, "''")}'`;
const qn = (v) => (v == null || v === '' ? 'null' : q(v));
const arr = (xs) => `ARRAY[${xs.map(q).join(', ')}]::text[]`;

const catRows = categories
  .map(
    (c, i) =>
      `  (${q(c.slug)}, ${q(c.name)}, ${q(c.description)}, ${q(c.glyph)}, ${q(c.color)}, ${i})`
  )
  .join(',\n');

const pluginRows = plugins
  .map(
    (p) =>
      `  (${q(p.slug)}, ${q(p.name)}, ${q(p.displayName)}, ${q(p.description)}, ${q(
        p.longDescription
      )}, ${q(p.category)}, ${q(p.kind)}, ${arr(p.keywords)}, ${q(p.invocation)}, ${q(p.color)}, ${q(
        p.glyph
      )}, ${q(p.version)}, ${q(p.license)}, ${q(p.author.name)}, ${q(p.author.url)}, ${q(
        p.source
      )}, ${p.featured ? 'true' : 'false'}, ${p.community ? 'true' : 'false'}, ${qn(p.repo)}, ${qn(
        p.homepage
      )})`
  )
  .join(',\n');

const seedSql = `-- Generated by scripts/build-catalog.mjs from src/data/catalog.json — do not edit by hand.
-- Idempotent: safe to re-run. Apply after the migrations in supabase/migrations/.

insert into public.categories (slug, name, description, glyph, color, sort) values
${catRows}
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  glyph = excluded.glyph,
  color = excluded.color,
  sort = excluded.sort;

insert into public.plugins (
  slug, name, display_name, description, long_description, category, kind, keywords,
  invocation, color, glyph, version, license, author_name, author_url, source, featured,
  community, repo, homepage
) values
${pluginRows}
on conflict (slug) do update set
  name = excluded.name,
  display_name = excluded.display_name,
  description = excluded.description,
  long_description = excluded.long_description,
  category = excluded.category,
  kind = excluded.kind,
  keywords = excluded.keywords,
  invocation = excluded.invocation,
  color = excluded.color,
  glyph = excluded.glyph,
  version = excluded.version,
  license = excluded.license,
  author_name = excluded.author_name,
  author_url = excluded.author_url,
  source = excluded.source,
  featured = excluded.featured,
  community = excluded.community,
  repo = excluded.repo,
  homepage = excluded.homepage,
  updated_at = now();
`;

mkdirSync(resolve(root, 'supabase'), { recursive: true });
writeFileSync(resolve(root, 'supabase/seed.sql'), seedSql);

const community = plugins.filter(isCommunity).length;
console.log(
  `Generated:\n  .claude-plugin/marketplace.json (${plugins.length} plugins, ${community} community)\n  public/marketplace.json\n  supabase/seed.sql (${categories.length} categories, ${plugins.length} plugins)`
);
