/**
 * Bundled catalog — typed view over the single source of truth (src/data/catalog.json).
 *
 * That same JSON drives: (1) this instant website render, (2) the Supabase seed in
 * supabase/seed.sql, and (3) both marketplace manifests — all generated by
 * scripts/build-catalog.mjs. Keep each plugin's `slug` === its folder name under /plugins.
 */

import catalog from '@/data/catalog.json';
import type { Category, Plugin } from '@/data/types';

export const CATEGORIES: Category[] = catalog.categories as Category[];

export const PLUGINS: Plugin[] = (catalog.plugins as Plugin[]).map((p) => ({
  ...p,
  kind: p.kind === 'agent' ? 'agent' : 'skill',
}));

export const MARKETPLACE_META = catalog.marketplace;
